language: python
python: 2.7
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg -v 2.2.1
  - bin/buildout -c travis.cfg -N
script:
  - bin/i18n cpskin
  - bin/i18n plone
  - bin/test
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.org#affinitic"
      - "irc.freenode.org#imio"
    on_success: change
    on_failure: always
